import { Body, Controller, Delete, Get, Inject, Param, Patch, Post, Put, Req, UseGuards } from '@nestjs/common';
import { z } from 'zod';
import { idSchema, localized, parseBody, SessionGuard, type AuthenticatedRequest } from './common';
import { PrismaService } from './prisma.service';

const pageInput = z.object({ title: localized, slug: z.string().regex(/^[a-z0-9-]+$/), description: localized, visibility: z.enum(['PUBLIC', 'DRAFT', 'UNLISTED']).optional(), published: z.boolean().optional() });
const blockInput = z.object({ type: z.string().min(1).max(64), title: localized.nullable().optional(), subtitle: localized.nullable().optional(), content: localized.nullable().optional(), url: z.string().url().nullable().optional(), config: z.record(z.string(), z.unknown()).default({}), visible: z.boolean().default(true), startsAt: z.coerce.date().nullable().optional(), endsAt: z.coerce.date().nullable().optional() });
const blockPatch = blockInput.partial().extend({ expectedVersion: z.number().int().positive() });
const hasProfile = async (prisma: PrismaService, userId: string, profileId: string) => prisma.profile.findFirst({ where: { id: profileId, ownerUserId: userId }, select: { id: true } });

@Controller('api/v1/profiles/:profileId/pages')
@UseGuards(SessionGuard)
export class PageController {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
  @Get()
  async list(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string) { const owner = await hasProfile(this.prisma, req.user!.id, parseBody(idSchema, profileId)); if (!owner) return { ok: false, error: { code: 'not_found', message: 'Profile not found.' } }; const pages = await this.prisma.page.findMany({ where: { profileId }, orderBy: { position: 'asc' }, include: { blocks: { orderBy: { position: 'asc' } } } }); return { ok: true, data: pages }; }
  @Post()
  async create(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Body() body: unknown) { const id = parseBody(idSchema, profileId); if (!(await hasProfile(this.prisma, req.user!.id, id))) return { ok: false, error: { code: 'not_found', message: 'Profile not found.' } }; const input = parseBody(pageInput, body); const page = await this.prisma.page.create({ data: { profileId: id, title: input.title, slug: input.slug, description: input.description, visibility: input.visibility ?? 'DRAFT', published: input.published ?? false, position: await this.prisma.page.count({ where: { profileId: id } }) } }); return { ok: true, data: page }; }
  @Patch(':pageId')
  async update(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Param('pageId') pageId: string, @Body() body: unknown) { const input = parseBody(pageInput.partial().extend({ expectedVersion: z.number().int().positive() }), body); const page = await this.prisma.page.findFirst({ where: { id: pageId, profileId, profile: { ownerUserId: req.user!.id } } }); if (!page) return { ok: false, error: { code: 'not_found', message: 'Page not found.' } }; if (page.version !== input.expectedVersion) return { ok: false, error: { code: 'conflict', message: 'Page changed since it was opened.', currentVersion: page.version } }; const { expectedVersion: _, ...patch } = input; return { ok: true, data: await this.prisma.page.update({ where: { id: pageId }, data: { ...patch, version: { increment: 1 } } }) }; }
  @Delete(':pageId')
  async remove(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Param('pageId') pageId: string) { const deleted = await this.prisma.page.deleteMany({ where: { id: pageId, profileId, profile: { ownerUserId: req.user!.id } } }); return deleted.count ? { ok: true, data: null } : { ok: false, error: { code: 'not_found', message: 'Page not found.' } }; }
  @Post(':pageId/duplicate')
  async duplicate(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Param('pageId') pageId: string) { const source = await this.prisma.page.findFirst({ where: { id: pageId, profileId, profile: { ownerUserId: req.user!.id } }, include: { blocks: { orderBy: { position: 'asc' } } } }); if (!source) return { ok: false, error: { code: 'not_found', message: 'Page not found.' } }; const slug = `${source.slug}-copy-${Date.now().toString(36)}`; const page = await this.prisma.page.create({ data: { profileId, title: source.title as any, slug, description: source.description as any, published: false, visibility: 'DRAFT', position: await this.prisma.page.count({ where: { profileId } }), blocks: { create: source.blocks.map(({ id: _id, pageId: _pageId, parentId: _parentId, createdAt: _createdAt, updatedAt: _updatedAt, version: _version, ...block }) => ({ ...block, title: block.title as any, subtitle: block.subtitle as any, content: block.content as any, config: block.config as any })) as any } }, include: { blocks: { orderBy: { position: 'asc' } } } }); return { ok: true, data: page }; }
  @Put('order')
  async reorder(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Body() body: unknown) { const input = parseBody(z.object({ orderedPageIds: z.array(idSchema).min(1) }), body); const pages = await this.prisma.page.findMany({ where: { profileId, profile: { ownerUserId: req.user!.id } }, select: { id: true } }); if (pages.length !== input.orderedPageIds.length || new Set(input.orderedPageIds).size !== pages.length || pages.some(({ id }) => !input.orderedPageIds.includes(id))) return { ok: false, error: { code: 'validation', message: 'The page order must contain every page exactly once.' } }; await this.prisma.$transaction(input.orderedPageIds.map((id, position) => this.prisma.page.update({ where: { id }, data: { position, version: { increment: 1 } } }))); return { ok: true, data: await this.prisma.page.findMany({ where: { profileId }, orderBy: { position: 'asc' } }) }; }
}

@Controller('api/v1/pages/:pageId/blocks')
@UseGuards(SessionGuard)
export class BlockController {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
  @Get()
  async list(@Req() req: AuthenticatedRequest, @Param('pageId') pageId: string) { const page = await this.prisma.page.findFirst({ where: { id: pageId, profile: { ownerUserId: req.user!.id } } }); if (!page) return { ok: false, error: { code: 'not_found', message: 'Page not found.' } }; return { ok: true, data: await this.prisma.block.findMany({ where: { pageId }, orderBy: { position: 'asc' } }) }; }
  @Post()
  async create(@Req() req: AuthenticatedRequest, @Param('pageId') pageId: string, @Body() body: unknown) { const page = await this.prisma.page.findFirst({ where: { id: pageId, profile: { ownerUserId: req.user!.id } } }); if (!page) return { ok: false, error: { code: 'not_found', message: 'Page not found.' } }; const input = parseBody(blockInput, body); return { ok: true, data: await this.prisma.block.create({ data: { pageId, ...input, config: input.config as any, title: input.title as any, subtitle: input.subtitle as any, content: input.content as any, position: await this.prisma.block.count({ where: { pageId } }) } }) }; }
  @Patch(':blockId')
  async update(@Req() req: AuthenticatedRequest, @Param('pageId') pageId: string, @Param('blockId') blockId: string, @Body() body: unknown) { const input = parseBody(blockPatch, body); const block = await this.prisma.block.findFirst({ where: { id: blockId, pageId, page: { profile: { ownerUserId: req.user!.id } } } }); if (!block) return { ok: false, error: { code: 'not_found', message: 'Block not found.' } }; if (block.version !== input.expectedVersion) return { ok: false, error: { code: 'conflict', message: 'Block changed since it was opened.', currentVersion: block.version } }; const { expectedVersion: _, ...patch } = input; return { ok: true, data: await this.prisma.block.update({ where: { id: blockId }, data: { ...(patch as any), version: { increment: 1 } } }) }; }
  @Delete(':blockId')
  async remove(@Req() req: AuthenticatedRequest, @Param('pageId') pageId: string, @Param('blockId') blockId: string) { const deleted = await this.prisma.block.deleteMany({ where: { id: blockId, pageId, page: { profile: { ownerUserId: req.user!.id } } } }); return deleted.count ? { ok: true, data: null } : { ok: false, error: { code: 'not_found', message: 'Block not found.' } }; }
  @Post(':blockId/duplicate')
  async duplicate(@Req() req: AuthenticatedRequest, @Param('pageId') pageId: string, @Param('blockId') blockId: string) { const source = await this.prisma.block.findFirst({ where: { id: blockId, pageId, page: { profile: { ownerUserId: req.user!.id } } } }); if (!source) return { ok: false, error: { code: 'not_found', message: 'Block not found.' } }; const block = await this.prisma.block.create({ data: { pageId, parentId: source.parentId, type: source.type, title: source.title as any, subtitle: source.subtitle as any, content: source.content as any, url: source.url, config: source.config as any, visible: source.visible, startsAt: source.startsAt, endsAt: source.endsAt, position: source.position + 1 } }); await this.prisma.block.updateMany({ where: { pageId, id: { not: block.id }, position: { gt: source.position } }, data: { position: { increment: 1 } } }); return { ok: true, data: block }; }
  @Patch(':blockId/visibility')
  async setVisible(@Req() req: AuthenticatedRequest, @Param('pageId') pageId: string, @Param('blockId') blockId: string, @Body() body: unknown) { const input = parseBody(z.object({ visible: z.boolean(), expectedVersion: z.number().int().positive() }), body); const updated = await this.prisma.block.updateMany({ where: { id: blockId, pageId, version: input.expectedVersion, page: { profile: { ownerUserId: req.user!.id } } }, data: { visible: input.visible, version: { increment: 1 } } }); if (!updated.count) return { ok: false, error: { code: 'conflict', message: 'Block not found or changed since it was opened.' } }; return { ok: true, data: await this.prisma.block.findUnique({ where: { id: blockId } }) }; }
  @Put('order')
  async reorder(@Req() req: AuthenticatedRequest, @Param('pageId') pageId: string, @Body() body: unknown) { const input = parseBody(z.object({ orderedBlockIds: z.array(idSchema).min(1) }), body); const page = await this.prisma.page.findFirst({ where: { id: pageId, profile: { ownerUserId: req.user!.id } } }); if (!page) return { ok: false, error: { code: 'not_found', message: 'Page not found.' } }; const blocks = await this.prisma.block.findMany({ where: { pageId }, select: { id: true } }); if (blocks.length !== input.orderedBlockIds.length || new Set(input.orderedBlockIds).size !== blocks.length || blocks.some(({ id }) => !input.orderedBlockIds.includes(id))) return { ok: false, error: { code: 'validation', message: 'The block order must contain every block exactly once.' } }; await this.prisma.$transaction(input.orderedBlockIds.map((id, position) => this.prisma.block.update({ where: { id }, data: { position, version: { increment: 1 } } }))); return { ok: true, data: await this.prisma.block.findMany({ where: { pageId }, orderBy: { position: 'asc' } }) }; }
}

@Controller('api/v1/profiles/:profileId/theme')
@UseGuards(SessionGuard)
export class ThemeController {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
  @Get()
  async get(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string) { const profile = await this.prisma.profile.findFirst({ where: { id: profileId, ownerUserId: req.user!.id }, select: { theme: true, version: true } }); return profile ? { ok: true, data: profile.theme } : { ok: false, error: { code: 'not_found', message: 'Profile not found.' } }; }
  @Put()
  async save(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Body() body: unknown) { const input = parseBody(z.object({ theme: z.record(z.string(), z.unknown()), expectedVersion: z.number().int().positive() }), body); const profile = await this.prisma.profile.findFirst({ where: { id: profileId, ownerUserId: req.user!.id } }); if (!profile) return { ok: false, error: { code: 'not_found', message: 'Profile not found.' } }; if (profile.version !== input.expectedVersion) return { ok: false, error: { code: 'conflict', message: 'Profile changed since it was opened.', currentVersion: profile.version } }; const saved = await this.prisma.profile.update({ where: { id: profileId }, data: { theme: input.theme as any, version: { increment: 1 } }, select: { theme: true } }); return { ok: true, data: saved.theme }; }
}
