import { Body, Controller, Delete, Get, Inject, Param, Patch, Post, Req, UseGuards } from '@nestjs/common';
import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import { z } from 'zod';
import { Prisma } from '@prisma/client';
import { idSchema, parseBody, SessionGuard, type AuthenticatedRequest } from './common';
import { loadConfig } from './config';
import { PrismaService } from './prisma.service';

const owned = (prisma: PrismaService, userId: string, profileId: string) => prisma.profile.findFirst({ where: { id: profileId, ownerUserId: userId }, select: { id: true } });
const encrypt = (value: string) => { const key = createHash('sha256').update(process.env.SESSION_SECRET ?? '').digest(); const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', key, iv); const encrypted = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${encrypted.toString('base64url')}`; };
const decrypt = (value: string) => { const key = createHash('sha256').update(process.env.SESSION_SECRET ?? '').digest(); const [iv, tag, data] = value.split('.').map((part) => Buffer.from(part, 'base64url')); const decipher = createDecipheriv('aes-256-gcm', key, iv); decipher.setAuthTag(tag); return Buffer.concat([decipher.update(data), decipher.final()]).toString('utf8'); };

@Controller('api/v1/profiles/:profileId/domains')
@UseGuards(SessionGuard)
export class DomainController {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
  @Get() async list(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string) { if (!(await owned(this.prisma, req.user!.id, profileId))) return { ok: false, error: { code: 'not_found', message: 'Profile not found.' } }; return { ok: true, data: await this.prisma.customDomain.findMany({ where: { profileId }, orderBy: { createdAt: 'asc' } }) }; }
  @Post() async add(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Body() body: unknown) { if (!(await owned(this.prisma, req.user!.id, profileId))) return { ok: false, error: { code: 'not_found', message: 'Profile not found.' } }; const { hostname } = parseBody(z.object({ hostname: z.string().trim().toLowerCase().regex(/^(?=.{1,253}$)(?!-)(?:[a-z0-9-]{1,63}\.)+[a-z]{2,63}$/) }), body); const token = `raloa-domain-${randomBytes(18).toString('hex')}`; const domain = await this.prisma.customDomain.create({ data: { profileId, hostname, verificationToken: token, records: [{ type: 'TXT', name: `_raloa.${hostname}`, value: token }], ssl: 'NONE' } }); await this.cloudflare('POST', `/accounts/${loadConfig().CLOUDFLARE_ACCOUNT_ID}/custom-hostnames`, { hostname, ssl: { method: 'http', type: 'dv', settings: { min_tls_version: '1.2' } } }, true).catch(() => undefined); return { ok: true, data: domain }; }
  @Post(':domainId/verify') async verify(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Param('domainId') domainId: string) { const domain = await this.prisma.customDomain.findFirst({ where: { id: domainId, profileId, profile: { ownerUserId: req.user!.id } } }); if (!domain) return { ok: false, error: { code: 'not_found', message: 'Domain not found.' } }; const records = domain.records as Array<{ name: string; value: string }>; let verified = false; try { const result = await fetch(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(records[0].name)}&type=TXT`, { headers: { accept: 'application/dns-json' } }); const json = await result.json() as { Answer?: Array<{ data: string }> }; verified = Boolean(json.Answer?.some((answer) => answer.data.includes(domain.verificationToken))); } catch { verified = false; } const saved = await this.prisma.customDomain.update({ where: { id: domain.id }, data: { status: verified ? 'VERIFIED' : 'VERIFYING', ssl: verified ? 'PROVISIONING' : 'NONE', lastCheckedAt: new Date(), detail: verified ? null : 'TXT verification record not found.' } }); return { ok: true, data: saved }; }
  @Patch(':domainId/primary') async primary(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Param('domainId') domainId: string) { const domain = await this.prisma.customDomain.findFirst({ where: { id: domainId, profileId, profile: { ownerUserId: req.user!.id } } }); if (!domain || domain.status !== 'VERIFIED') return { ok: false, error: { code: 'validation', message: 'Only verified domains can be primary.' } }; await this.prisma.$transaction([this.prisma.customDomain.updateMany({ where: { profileId }, data: { isPrimary: false } }), this.prisma.customDomain.update({ where: { id: domainId }, data: { isPrimary: true } })]); return { ok: true, data: await this.prisma.customDomain.findMany({ where: { profileId }, orderBy: { createdAt: 'asc' } }) }; }
  @Delete(':domainId') async remove(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Param('domainId') domainId: string) { const result = await this.prisma.customDomain.deleteMany({ where: { id: domainId, profileId, profile: { ownerUserId: req.user!.id } } }); return result.count ? { ok: true, data: null } : { ok: false, error: { code: 'not_found', message: 'Domain not found.' } }; }
  private async cloudflare(method: string, path: string, body?: unknown, optional = false) { const config = loadConfig(); if (!config.CLOUDFLARE_API_TOKEN || !config.CLOUDFLARE_ACCOUNT_ID) { if (optional) return null; throw new Error('Cloudflare is not configured.'); } const response = await fetch(`https://api.cloudflare.com/client/v4${path}`, { method, headers: { authorization: `Bearer ${config.CLOUDFLARE_API_TOKEN}`, 'content-type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); if (!response.ok) throw new Error('Cloudflare request failed.'); return response.json(); }
}

@Controller('api/v1/profiles/:profileId/integrations')
@UseGuards(SessionGuard)
export class IntegrationController {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
  @Get() async list(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string) { if (!(await owned(this.prisma, req.user!.id, profileId))) return { ok: false, error: { code: 'not_found', message: 'Profile not found.' } }; const items = await this.prisma.integration.findMany({ where: { profileId } }); return { ok: true, data: items.map(({ config: _config, ...item }) => ({ ...item, demo: true })) }; }
  @Post(':kind/connect') async connect(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Param('kind') kind: string, @Body() body: unknown) { if (!(await owned(this.prisma, req.user!.id, profileId))) return { ok: false, error: { code: 'not_found', message: 'Profile not found.' } }; const input = parseBody(z.object({ handle: z.string().trim().min(1).max(200), accessToken: z.string().optional() }), body); const normalized = kind.toUpperCase().replace('-', '_') as 'INSTAGRAM' | 'GA4' | 'META_PIXEL'; if (!['INSTAGRAM', 'GA4', 'META_PIXEL'].includes(normalized)) return { ok: false, error: { code: 'validation', message: 'Unsupported integration.' } }; let account: any = { handle: input.handle, connectedAt: new Date().toISOString() }; if (normalized === 'INSTAGRAM') { if (!input.accessToken) return { ok: false, error: { code: 'validation', message: 'Instagram access token is required.' } }; const result = await fetch(`https://graph.instagram.com/me?fields=id,username,profile_picture_url&access_token=${encodeURIComponent(input.accessToken)}`); if (!result.ok) return { ok: false, error: { code: 'validation', message: 'Instagram token was rejected.' } }; account = { ...(await result.json()), connectedAt: new Date().toISOString() }; } const item = await this.prisma.integration.upsert({ where: { profileId_kind: { profileId, kind: normalized } }, update: { state: 'CONNECTED', enabled: true, account, config: input.accessToken ? { accessToken: encrypt(input.accessToken) } : undefined, syncState: 'idle', detail: null }, create: { profileId, kind: normalized, state: 'CONNECTED', enabled: true, account, config: input.accessToken ? { accessToken: encrypt(input.accessToken) } : undefined } }); return { ok: true, data: { ...item, config: undefined, demo: true } }; }
  @Post(':kind/disconnect') async disconnect(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Param('kind') kind: string) { const item = await this.prisma.integration.updateMany({ where: { profileId, kind: kind.toUpperCase().replace('-', '_') as any, profile: { ownerUserId: req.user!.id } }, data: { state: 'DISCONNECTED', enabled: false, config: Prisma.JsonNull } }); return item.count ? { ok: true, data: null } : { ok: false, error: { code: 'not_found', message: 'Integration not found.' } }; }
  @Patch(':kind/tracking') async tracking(@Req() req: AuthenticatedRequest, @Param('profileId') profileId: string, @Param('kind') kind: string, @Body() body: unknown) { if (!(await owned(this.prisma, req.user!.id, profileId))) return { ok: false, error: { code: 'not_found', message: 'Profile not found.' } }; const input = parseBody(z.object({ trackingId: z.string().trim().max(200), enabled: z.boolean() }), body); const item = await this.prisma.integration.upsert({ where: { profileId_kind: { profileId, kind: kind.toUpperCase().replace('-', '_') as any } }, update: { trackingId: input.trackingId, enabled: input.enabled }, create: { profileId, kind: kind.toUpperCase().replace('-', '_') as any, trackingId: input.trackingId, enabled: input.enabled } }); return { ok: true, data: { ...item, config: undefined, demo: true } }; }
}

@Controller('api/v1/templates')
export class TemplateController {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
  @Get() async list() { return { ok: true, data: await this.prisma.template.findMany({ orderBy: [{ isFeatured: 'desc' }, { updatedAt: 'desc' }] }) }; }
  @Get(':templateId') async get(@Param('templateId') templateId: string) { return { ok: true, data: await this.prisma.template.findUnique({ where: { id: templateId } }) }; }
  @Post(':templateId/apply') @UseGuards(SessionGuard) async apply(@Req() req: AuthenticatedRequest, @Param('templateId') templateId: string, @Body() body: unknown) { const input = parseBody(z.object({ profileId: idSchema, keepSocials: z.boolean().default(true) }), body); const template = await this.prisma.template.findUnique({ where: { id: templateId } }); if (!template || !(await owned(this.prisma, req.user!.id, input.profileId))) return { ok: false, error: { code: 'not_found', message: 'Template or profile not found.' } }; const pages = template.pages as Array<{ title: unknown; slug: string; description?: unknown; blocks: Array<Record<string, unknown>> }>; const result = await this.prisma.$transaction(async (tx) => { const old = await tx.page.findMany({ where: { profileId: input.profileId }, include: { blocks: true } }); await tx.page.deleteMany({ where: { profileId: input.profileId } }); for (const [position, page] of pages.entries()) await tx.page.create({ data: { profileId: input.profileId, title: page.title as any, slug: `${page.slug}-${Date.now().toString(36).slice(-3)}`, description: (page.description ?? {}) as any, position, published: false, visibility: 'DRAFT', blocks: { create: page.blocks.map((block, index) => ({ type: String(block.type), title: block.title as any, subtitle: block.subtitle as any, content: block.content as any, url: block.url ? String(block.url) : null, config: (block.config ?? {}) as any, position: index })) } } }); return old; }); return { ok: true, data: { profileId: input.profileId, replacedPages: result.length, replacedBlocks: result.reduce((sum, page) => sum + page.blocks.length, 0), preservedFields: [input.keepSocials ? 'socials' : 'identity', 'identity', 'seo', 'media'] } }; }
}
