import { Body, Controller, Get, Inject, Param, Post, Req, UseGuards } from '@nestjs/common';
import { z } from 'zod';
import { idSchema, parseBody, SessionGuard, type AuthenticatedRequest } from './common';
import { PrismaService } from './prisma.service';

const itemSchema = z.object({ title: z.union([z.string(), z.record(z.string(), z.string())]), subtitle: z.union([z.string(), z.record(z.string(), z.string())]).optional(), url: z.string().url().optional(), type: z.string().optional() });
const normalize = (value: unknown) => { const input = z.object({ title: z.union([z.string(), z.record(z.string(), z.string())]), blocks: z.array(itemSchema).optional() }).parse(value); return { title: input.title, blocks: input.blocks ?? [] }; };

@Controller('api/v1/imports')
@UseGuards(SessionGuard)
export class ImportController {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
  @Post()
  async start(@Req() req: AuthenticatedRequest, @Body() body: unknown) { const input = parseBody(z.object({ source: z.enum(['linktree', 'urlswerv', 'raloa-json']), input: z.string().min(1).max(1_000_000) }), body); const job = await this.prisma.importJob.create({ data: { userId: req.user!.id, source: input.source.toUpperCase().replace('-', '_') as any, input: input.input, status: 'PARSING', progress: 25 } }); try { let raw: unknown; if (input.source === 'raloa-json') raw = JSON.parse(input.input); else { const url = new URL(input.input); if (url.protocol !== 'https:' || this.privateHost(url.hostname)) throw new Error('Only public HTTPS import URLs are allowed.'); const response = await fetch(url, { signal: AbortSignal.timeout(10_000), headers: { accept: 'application/json,text/html' } }); if (!response.ok) throw new Error('Import source returned an error.'); const text = await response.text(); raw = text.trim().startsWith('{') ? JSON.parse(text) : { title: url.hostname, blocks: [...text.matchAll(/href=["'](https?:\/\/[^"']+)["']/gi)].slice(0, 100).map((match) => ({ title: match[1], url: match[1], type: 'link' })) }; } const normalized = normalize(raw); const preview = { jobId: job.id, source: input.source, handle: input.input, sourceUrl: input.input, items: normalized.blocks.map((block, index) => ({ id: `${job.id}-${index}`, kind: 'block', type: block.type ?? 'link', title: typeof block.title === 'string' ? { en: block.title } : block.title, subtitle: typeof block.subtitle === 'string' ? { en: block.subtitle } : block.subtitle, url: block.url, selected: true })), warnings: [] }; const saved = await this.prisma.importJob.update({ where: { id: job.id }, data: { status: 'READY', progress: 100, preview: { ...preview, page: normalized.title } } }); return { ok: true, data: saved }; } catch (error) { await this.prisma.importJob.update({ where: { id: job.id }, data: { status: 'FAILED', error: error instanceof Error ? error.message : 'Import failed.' } }); return { ok: false, error: { code: 'validation', message: error instanceof Error ? error.message : 'Import failed.' } }; } }
  @Get(':jobId') async status(@Req() req: AuthenticatedRequest, @Param('jobId') jobId: string) { const job = await this.prisma.importJob.findFirst({ where: { id: jobId, userId: req.user!.id } }); return job ? { ok: true, data: job } : { ok: false, error: { code: 'not_found', message: 'Import job not found.' } }; }
  @Post(':jobId/commit') async commit(@Req() req: AuthenticatedRequest, @Param('jobId') jobId: string, @Body() body: unknown) { const input = parseBody(z.object({ profileId: idSchema, selectedItemIds: z.array(z.string()).optional() }), body); const job = await this.prisma.importJob.findFirst({ where: { id: jobId, userId: req.user!.id, status: 'READY' } }); const profile = await this.prisma.profile.findFirst({ where: { id: input.profileId, ownerUserId: req.user!.id } }); if (!job || !profile) return { ok: false, error: { code: 'not_found', message: 'Import job or profile not found.' } }; const preview = job.preview as any; const selected = new Set(input.selectedItemIds ?? preview.items.map((item: any) => item.id)); const blocks = preview.items.filter((item: any) => selected.has(item.id)); const page = await this.prisma.page.create({ data: { profileId: profile.id, title: preview.page ?? { en: 'Imported links' }, slug: `import-${Date.now().toString(36)}`, description: { en: 'Imported from an external profile.' }, visibility: 'DRAFT', blocks: { create: blocks.map((item: any, index: number) => ({ type: item.type ?? 'link', title: item.title, subtitle: item.subtitle, url: item.url, config: {}, position: index })) } }, include: { blocks: true } }); await this.prisma.importJob.update({ where: { id: job.id }, data: { status: 'COMMITTED', committedAt: new Date() } }); return { ok: true, data: { jobId, createdPages: 1, createdBlocks: page.blocks.length, skippedDuplicates: 0 } }; }
  private privateHost(host: string) { return host === 'localhost' || host === '127.0.0.1' || host === '::1' || host.startsWith('10.') || host.startsWith('192.168.') || /^172\.(1[6-9]|2\d|3[01])\./.test(host); }
}
